//
// TurboQuant-style data-oblivious vector quantization. Pure math, no I/O.
//
// Implements the core of "TurboQuant: Online Vector Quantization with
// Near-optimal Distortion Rate" (Google Research, arXiv:2504.19874, ICLR
// 2026): randomly rotate input vectors so coordinates become
// near-independent with a known concentrated distribution, then apply a
// FIXED precomputed optimal (Lloyd-Max) scalar quantizer per coordinate.
// No codebook training, no data-dependent state: codes are computable on
// the first add(). The MIT-licensed Rust reference is
// https://github.com/RyanCodrai/turbovec.
//
// Approximation note: after `ROTATION_ROUNDS` randomized Hadamard rounds,
// the coordinates of a unit vector are treated as i.i.d. N(0, 1/D). This is
// exact in the D→infinity limit and close for D >= 128. Real embeddings are
// anisotropic; the rotation Gaussianizes them and the optional rescore pass
// (see quantized-vector-index.ts) absorbs the residual error.
//
// We quantize the scaled coordinate sqrt(D) * x_i / ||x||, whose reference
// distribution is N(0, 1), so a single dimension-independent level table
// serves every index.

import { createHash } from "node:crypto";

export const TURBOQUANT_VERSION = 1;
export const ROTATION_ROUNDS = 3;

export type QuantBits = 2 | 4;

export function nextPow2(n: number): number {
  if (n <= 1) return 1;
  return 2 ** Math.ceil(Math.log2(n));
}

// ---------------------------------------------------------------------------
// Deterministic PRNG. The rotation must be reconstructible from params alone
// across processes, so Math.random is banned. mulberry32 is a tiny 32-bit
// generator with stable output for a given seed.

export function seedFromString(seed: string): number {
  // FNV-1a over UTF-16 code units, folded to uint32.
  let h = 0x811c9dc5;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * One Int8Array of ±1 per rotation round, length D each. Generated by
 * draining the PRNG in a fixed order, so (seed, D, rounds) fully determines
 * the rotation.
 */
export function buildSignFlips(
  prng: () => number,
  D: number,
  rounds: number,
): Int8Array[] {
  const flips: Int8Array[] = [];
  for (let r = 0; r < rounds; r++) {
    const s = new Int8Array(D);
    for (let i = 0; i < D; i++) {
      s[i] = prng() < 0.5 ? -1 : 1;
    }
    flips.push(s);
  }
  return flips;
}

// ---------------------------------------------------------------------------
// Fast Walsh-Hadamard Transform, in place, unnormalized. Callers rescale by
// 1/sqrt(D) per application to keep the transform orthonormal.

export function fwht(buf: Float32Array): void {
  const n = buf.length;
  for (let len = 1; len < n; len <<= 1) {
    for (let i = 0; i < n; i += len << 1) {
      for (let j = i; j < i + len; j++) {
        const a = buf[j] as number;
        const b = buf[j + len] as number;
        buf[j] = a + b;
        buf[j + len] = a - b;
      }
    }
  }
}

/**
 * Rotate `src` (length d <= D) into a length-D buffer: zero-pad, then
 * `signFlips.length` rounds of (sign flip, FWHT, 1/sqrt(D) rescale).
 * Norm-preserving up to f32 rounding. Non-finite inputs are sanitized to 0.
 * Pass `scratch` (length D) to avoid per-call allocation.
 */
export function rotate(
  src: Float32Array,
  D: number,
  signFlips: Int8Array[],
  scratch?: Float32Array,
): Float32Array {
  const out = scratch && scratch.length === D ? scratch : new Float32Array(D);
  for (let i = 0; i < src.length; i++) {
    const v = src[i] as number;
    out[i] = Number.isFinite(v) ? v : 0;
  }
  out.fill(0, src.length);
  const invSqrtD = 1 / Math.sqrt(D);
  for (const flips of signFlips) {
    for (let i = 0; i < D; i++) {
      out[i] = (out[i] as number) * (flips[i] as number);
    }
    fwht(out);
    for (let i = 0; i < D; i++) {
      out[i] = (out[i] as number) * invSqrtD;
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Lloyd-Max scalar quantizer for the standard normal, computed analytically
// at init (no data involved) and cached per bit width.

function normalPdf(x: number): number {
  return Math.exp(-0.5 * x * x) / Math.sqrt(2 * Math.PI);
}

// Abramowitz & Stegun 7.1.26 rational erf approximation (~1e-7 abs error).
function erf(z: number): number {
  const sign = z < 0 ? -1 : 1;
  const x = Math.abs(z);
  const t = 1 / (1 + 0.3275911 * x);
  const y =
    1 -
    (((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t -
      0.284496736) *
      t +
      0.254829592) *
      t) *
      Math.exp(-x * x);
  return sign * y;
}

function normalCdf(x: number): number {
  return 0.5 * (1 + erf(x / Math.SQRT2));
}

export interface LevelTable {
  levels: Float32Array; // 2^bits centroids, ascending
  boundaries: Float32Array; // 2^bits - 1 decision thresholds, ascending
}

const levelTableCache = new Map<QuantBits, LevelTable>();

/**
 * Lloyd-Max iteration for N(0,1): boundaries are midpoints of adjacent
 * levels; each level is the conditional mean of the cell. Converges in a
 * few dozen iterations; deterministic, so the table never needs persisting
 * (a short hash travels in index params to invalidate on algorithm change).
 */
export function lloydMaxLevels(bits: QuantBits): LevelTable {
  const cached = levelTableCache.get(bits);
  if (cached) return cached;

  const L = 2 ** bits;
  const INF = 8; // φ(8) ≈ 5e-15: numerically infinite for our purposes
  const levels = new Float64Array(L);
  for (let k = 0; k < L; k++) {
    levels[k] = -3 + (6 * (k + 0.5)) / L;
  }
  const bounds = new Float64Array(L - 1);

  for (let iter = 0; iter < 200; iter++) {
    for (let k = 0; k < L - 1; k++) {
      bounds[k] = ((levels[k] as number) + (levels[k + 1] as number)) / 2;
    }
    let moved = 0;
    for (let k = 0; k < L; k++) {
      const a = k === 0 ? -INF : (bounds[k - 1] as number);
      const b = k === L - 1 ? INF : (bounds[k] as number);
      const mass = normalCdf(b) - normalCdf(a);
      if (mass <= 0) continue;
      const centroid = (normalPdf(a) - normalPdf(b)) / mass;
      moved = Math.max(moved, Math.abs(centroid - (levels[k] as number)));
      levels[k] = centroid;
    }
    if (moved < 1e-10) break;
  }

  const table: LevelTable = {
    levels: Float32Array.from(levels),
    boundaries: Float32Array.from(bounds),
  };
  levelTableCache.set(bits, table);
  return table;
}

export function levelTableHash(bits: QuantBits): string {
  const { levels } = lloydMaxLevels(bits);
  const repr = Array.from(levels, (v) => v.toFixed(6)).join(",");
  return createHash("sha256").update(repr).digest("hex").slice(0, 16);
}

// ---------------------------------------------------------------------------
// Code packing. 4-bit: two codes per byte (even index in the low nibble);
// 2-bit: four codes per byte (index i in bits 2*(i % 4)).

export function packCodes(codeIndices: Uint8Array, bits: QuantBits): Uint8Array {
  const D = codeIndices.length;
  if (bits === 4) {
    const out = new Uint8Array(Math.ceil(D / 2));
    for (let i = 0; i < D; i++) {
      const c = (codeIndices[i] as number) & 0xf;
      if (i % 2 === 0) out[i >> 1] = c;
      else out[i >> 1] = (out[i >> 1] as number) | (c << 4);
    }
    return out;
  }
  const out = new Uint8Array(Math.ceil(D / 4));
  for (let i = 0; i < D; i++) {
    const c = (codeIndices[i] as number) & 0x3;
    out[i >> 2] = (out[i >> 2] as number) | (c << ((i % 4) * 2));
  }
  return out;
}

export function unpackCodes(
  packed: Uint8Array,
  D: number,
  bits: QuantBits,
): Uint8Array {
  const out = new Uint8Array(D);
  if (bits === 4) {
    for (let i = 0; i < D; i++) {
      const byte = packed[i >> 1] as number;
      out[i] = i % 2 === 0 ? byte & 0xf : (byte >> 4) & 0xf;
    }
    return out;
  }
  for (let i = 0; i < D; i++) {
    const byte = packed[i >> 2] as number;
    out[i] = (byte >> ((i % 4) * 2)) & 0x3;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Encode / score.

/**
 * Quantize an already-rotated length-D buffer. Returns the packed codes and
 * the original vector norm (rotation is norm-preserving, so this is also
 * the pre-rotation norm). A zero/degenerate vector encodes with norm 0 and
 * the code of the level nearest zero.
 */
export function encodeRotated(
  rotated: Float32Array,
  D: number,
  bits: QuantBits,
): { codes: Uint8Array; norm: number } {
  const { boundaries } = lloydMaxLevels(bits);
  let normSq = 0;
  for (let i = 0; i < D; i++) {
    const v = rotated[i] as number;
    normSq += v * v;
  }
  const norm = Math.sqrt(normSq);
  const scale = norm === 0 ? 0 : Math.sqrt(D) / norm;
  const nB = boundaries.length;
  const idx = new Uint8Array(D);
  for (let i = 0; i < D; i++) {
    const z = (rotated[i] as number) * scale;
    // Binary search: count of boundaries < z is the code.
    let lo = 0;
    let hi = nB;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if ((boundaries[mid] as number) < z) lo = mid + 1;
      else hi = mid;
    }
    idx[i] = lo;
  }
  return { codes: packCodes(idx, bits), norm };
}

/**
 * Asymmetric partial inner product: Σ rotatedQuery[i] * LEVELS[code_i].
 * The query stays full precision (rotated once per search); codes are read
 * nibble/crumb-wise without unpacking allocations. f64 accumulation.
 *
 * Cosine estimate for a stored vector v: asymmetricDot / (sqrt(D) * |q|),
 * because stored codes approximate sqrt(D) * v_i / ||v||.
 */
export function asymmetricDot(
  rotatedQuery: Float32Array,
  codes: Uint8Array,
  D: number,
  bits: QuantBits,
  table?: LevelTable,
): number {
  const { levels } = table ?? lloydMaxLevels(bits);
  let sum = 0;
  if (bits === 4) {
    for (let i = 0; i < D; i++) {
      const byte = codes[i >> 1] as number;
      const code = i % 2 === 0 ? byte & 0xf : (byte >> 4) & 0xf;
      sum += (rotatedQuery[i] as number) * (levels[code] as number);
    }
    return sum;
  }
  for (let i = 0; i < D; i++) {
    const byte = codes[i >> 2] as number;
    const code = (byte >> ((i % 4) * 2)) & 0x3;
    sum += (rotatedQuery[i] as number) * (levels[code] as number);
  }
  return sum;
}
