/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * One search result batch: `ids[i]` scored `scores[i]`, best first.
 * Length is `min(k, len, allowlist size)` — turbovec does not pad.
 */
export interface SearchHits {
  ids: BigUint64Array
  scores: Float32Array
}
export declare class TurbovecIndex {
  /**
   * `dims` must be a positive multiple of 8 and <= 65536;
   * `bitWidth` one of 2, 3, 4.
   */
  constructor(dims: number, bitWidth: number)
  /**
   * Add `ids.length` vectors from a flat f32 buffer of length
   * `ids.length * dims`. Rejects duplicate ids (in the index or the
   * batch), shape mismatches, and non-finite coordinates — atomically:
   * on error nothing was added.
   */
  addWithIds(vectors: Float32Array, ids: BigUint64Array): void
  /** O(1). Returns true when the id was present and removed. */
  remove(id: bigint): boolean
  /** True when a vector with this external id is stored. */
  contains(id: bigint): boolean
  /**
   * Top-`k` for a single query vector (length `dims`). When `allowlist`
   * is given, only those external ids can be returned; ids in the
   * allowlist that are not (or no longer) in the index are ignored, and
   * an effectively empty allowlist yields an empty result — never a panic.
   */
  search(query: Float32Array, k: number, allowlist?: BigUint64Array | undefined | null): SearchHits
  /** Persist to a `.tvim` file (turbovec format v3, validated on load). */
  save(path: string): void
  /** Load a `.tvim` file previously written by `save`. */
  static load(path: string): TurbovecIndex
  /** Number of stored vectors. */
  get len(): number
  /** Vector dimensionality this index was constructed with. */
  get dims(): number
  /** Bits per coordinate (2, 3 or 4). */
  get bitWidth(): number
}
